/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlykho;

import Entity.GiaSach;
import Entity.Kho;
import Repository.GiaRepository;
import Repository.GiaRepositoryImp;
import Repository.KhoRepository;
import Repository.KhoRepositoryImp;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class XemGiaSach extends javax.swing.JFrame {

    private KhoRepository khoRepository = new KhoRepositoryImp();
    private GiaRepository giaRepository = new GiaRepositoryImp();

    private DefaultComboBoxModel<String> setKho(DefaultComboBoxModel<String> comboBoxModel) {
        ArrayList<Kho> khos = khoRepository.getAll();
        comboBoxModel.addElement("Tất cả");
        for (Kho kho : khos) {
            comboBoxModel.addElement(kho.getTenKho());
        }
        return comboBoxModel;
    }

    private void setListGia(String kho, DefaultTableModel defaultTableModel) {
        defaultTableModel.setRowCount(0);
        ArrayList<Kho> khos = khoRepository.getAll();
        if (kho.compareToIgnoreCase("Tất cả") == 0) {
            ArrayList<GiaSach> giaSachs = giaRepository.getAll();
            giaSachs.stream().forEach(x -> defaultTableModel.addRow(new Object[]{x.getId(), x.getTenGia(), x.getViTri()}));
        } else {
            Integer khoId = null;
            for (Kho k : khos) {
                if (k.getTenKho().equalsIgnoreCase(kho)) {
                    khoId = k.getId();
                    break;
                }
            }
            if (khoId != null) {
                ArrayList<GiaSach> giaSachs = giaRepository.getGiaByKhoId(khoId);
                giaSachs.stream().forEach((x) -> {
                    defaultTableModel.addRow(new Object[]{x.getId(), x.getTenGia(), x.getViTri()});
                });
            } else {
                JOptionPane.showMessageDialog(this, "không tìm thấy kho");
            }
        }

    }

    public XemGiaSach() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        DefaultTableModel defaultTableModel = (DefaultTableModel) listGia.getModel();
        listKho.setModel(setKho(new DefaultComboBoxModel<>()));
        setListGia("Tất cả", defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listKho = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listGia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listKhoActionPerformed(evt);
            }
        });

        listGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã giá", "Tên giá", "Vị trí"
            }
        ));
        jScrollPane1.setViewportView(listGia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(listKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(listKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listKhoActionPerformed
        DefaultTableModel defaultTableModel = (DefaultTableModel) listGia.getModel();
        String value = (String) listKho.getSelectedItem();
        setListGia(value, defaultTableModel);
    }//GEN-LAST:event_listKhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemGiaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemGiaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemGiaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemGiaSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemGiaSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listGia;
    private javax.swing.JComboBox<String> listKho;
    // End of variables declaration//GEN-END:variables
}
